config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :friendships, only: [:index, :edit, :update] 
  get 'welcome/index'

  devise_for :users, :controllers => {:registrations => "registrations"}

  root 'welcome#index'
  resources :users, only: [:index, :show, :edit, :update]
  get 'friendships/send_friend_request' => 'friendships#send_friend_request', as: :send_friend_request
  get '/user_listing' => 'welcome#user_listing'
   get '/friend_list' => 'friendships#friend_list'






end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
    belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "500x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    validates :content, :presence => true
    # validates :image, attachment_presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  # has_attached_file :profile_image, styles: { medium: "300x300>", thumb: "500x500>" }, default_url: "/images/:style/missing.png"
  has_attached_file :profile_image, styles: { medium: "150x150>", thumb: "500x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :profile_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :profile_image, attachment_presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
    redirect_to root_path # Assuming you have a template named 'record_not_found'
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_filter :authenticate_user!, only: [:user_listing, :friend_list]
	def send_friend_request
		@friendship = current_user.friendships.create(:friend_id => params[:friend_id])
	  	if @friendship.save
	    	flash[:notice] = "Added friend."
	  	else
	    	flash[:error] = "Unable to add friend."
  		end	
  		  redirect_to :back and return
   	end

   	def friend_list
   	  @friends = current_user.friends
   	end

   	private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:user_id, :friend_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before login user cannot create the posts.
  # before_action :authenticate_user!, :except => [:index]
  # GET /posts
  # GET /posts.json
  def index
    if user_signed_in?
      ids = current_user.friends.pluck(:id) << current_user.id
      @posts = Post.where(user_id: ids)
    end 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
def new
    super
  end

  def create
  	super
    # add custom create logic here
  end

  def update
    super
  end

  def edit
  	super
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :profile_image)
  end

  def account_update_params
    params.require(:user).permit(:profile_image, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
	sign_out :user
	redirect_to welcome_index_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, only: :user_listing
  def index
  end
  def show
    render :index
  end
  def user_listing
    if user_signed_in?
   	  @users = User.all.reject{ |e| current_user.friends.include? e }.reject {|user| user == current_user}
  	end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/friend_list.html.erb
<!DOCTYPE>
<html>
<head>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Poiret+One" %>
<%= stylesheet_link_tag "bootstrap/css/bootstrap.min" %>
<style>
     td{padding:6px;}
     th{padding:6px;}

  *{
  font-family: 'Poiret One';
}
</style>
</head>
<body>

<center>

<p id="notice"><%= notice %></p>

<h1><B>Listing Friend</B></h1>
<% if @friends.present? %>
<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td align="center"><h3><B><%= friend.email %><h3></B></td>
         <td align="center"><h3><B><%= image_tag friend.profile_image.url(:medium) %><h3></B></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p><B>Currently you have no friend....</B></p>
 <% end %> 
<br>

<%= link_to 'Back', root_path,  :class => 'btn btn-primary' %>

</center>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flister</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<!DOCTYPE>
<html>
<head>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Poiret+One" %>
<%= stylesheet_link_tag "bootstrap/css/bootstrap.min" %>
<style>
     
  *{
  font-family: 'Poiret One';
}
body
{
  background-image: url('/assets/bg.jpg');
  color: #fff;
  
  background-size: cover;
}
     td{padding:6px;}

     
  .bg_color
  {
    height: 1000px;
    width: 100%;
    background-color: rgba(11,124,135,0.6) !important;
  }
  .links
  {
    color: #fff !important;
    font-size: 50px !important;
    font-weight: 100 !important;
    text-decoration: none !important;
    background: none;
  }
  .black_clr
  {
    color: #000;
  }
 input[type=submit]
  {
    background: none !important;
    border: 1px solid #fff !important;
    padding: 5px !important;
  }
a
{
    background: none !important;
    border: 1px solid #fff !important;
    padding: 7px !important;
    color: #fff !important;
    text-decoration: none !important;
    margin: 10px !important;
  }
 

</style>
</head>
<body>

<center>
<% if user_signed_in? %>
  <%= image_tag current_user.profile_image.url(:medium) %>
  <%= current_user.email %>
<% end %>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table border="0" style="margin-top:200px;font-size:18px;">
  <tr>
  <div class="field">
   <td> <%= f.label :attachment %></td>
    <td class="black_clr" style="font-family:sans-serif;">
        <%= f.file_field :image %></td>
    <%#= f.text_field :attachment %>
  </div>
</tr>
<tr>
  <div class="field">
    <td><%= f.label :content %></td>
    <td class="black_clr" style="font-family:sans-serif;"><%= f.text_area :content %></td>
  </div>
</tr>
<!-- <tr>
  <div class="field">
    <td><%#= f.label :user_id %></td>
    <td class="black_clr" style="font-family:sans-serif;"><%= f.text_field :user_id %></td>
  </div>
</tr> -->
<tr>
  <td></td>
  <div class="actions">
   <td> <%= f.submit %></td>
  </div>
<% end %>
</tr><br><br>
</table>
<br>
</center>
</body>
</html>

app/views/posts/edit.html.erb
<!DOCTYPE>
<html>
<head>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Poiret+One" %>
<%= stylesheet_link_tag "bootstrap/css/bootstrap.min" %>
	<style>   
*{
  font-family: 'Poiret One';
}
body
{
  background-image: url('/assets/bg.jpg');
  color: #fff;
  
  background-size: cover;
}
     td{padding:6px;}

     
  .bg_color
  {
    height: 1000px;
    width: 100%;
    background-color: rgba(11,124,135,0.6) !important;
  }
  .links
  {
    color: #fff !important;
    font-size: 50px !important;
    font-weight: 100 !important;
    text-decoration: none !important;
    background: none;
  }
  .black_clr
  {
    color: #000;
  }
 input[type=submit]
  {
    background: none !important;
    border: 1px solid #fff !important;
    padding: 5px !important;
  }
a
{
    background: none !important;
    border: 1px solid #fff !important;
    padding: 7px !important;
    color: #fff !important;
    text-decoration: none !important;
    margin: 10px !important;
  }
 
  
  
</style>
</head>
<body>
<div class="bg_color">
<center>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      
    </div>
    <div class="col-md-6">
      <h1 style="font-size:60px;font-weight:100;margin-top:50px;">EDITING POST</h1>
    </div>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @post %>&nbsp;&nbsp;&nbsp;
<%= link_to 'Back', posts_path %>

</center>
</div>
</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE>
<html>
<head>
<%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Poiret+One" %>
<%= stylesheet_link_tag "bootstrap/css/bootstrap.min" %>
<style>
td{padding:6px;}

 *{
  font-family: 'Poiret One';
}
body
{
  background-image: url('/assets/bg.jpg');
  background-size: cover;
  background-attachment: fixed;
  color:black;
  padding: 0 !important;
  margin: 0 !important;
}
  .bg_color
  {
    height: 100%;
    width: 100%;
    background-color: rgba(11,124,135,0.6) !important;
    background-attachment: fixed;
    
  }
  .links
  {
    color: white !important;
    font-size: 20px !important;
    font-weight: 100 !important;
    text-decoration: none !important;
    background: none;
  }
 .well
 {
  box-shadow: 5px 5px 5px #000 !important;
  border-radius: 5px !important;
 }

 input[type=submit]
  {
    background: none !important;
    border: 1px solid black !important;
    padding: 5px !important;
  }
a
{
    background: none !important;
    border: 1px solid black !important;
    padding: 7px !important;
    color: black !important;
    text-decoration: none !important;
  }  
</style>
</head>
<body>
<div class="bg_color">
<center>

<p id="notice"><%= notice %></p>

<h1 style="color:white">Listing Posts</h1>

<br>
<%= link_to 'New Post', new_post_path, :class => 'links' %>
<%= link_to 'Back', root_path, :class => 'links' %>
<br>
<% if @posts.present? %>  
  <%# abort @posts.collect(&:user_id).inspect %>
    <% @posts.each do |post| %>
    <br>
    <table border="0" class="well" style="border-radius:5px !important;">
     <tbody> 
      
       <tr style="background:#eee;font-family:sans-serif;"><td align="left" colspan="3" style="font-size:20px"><B><%= post.user.email %></B></td></tr>
       <tr style="background:#eee;font-family:sans-serif;"><td align="left" colspan="3" style="font-size:20px"><B><%= image_tag post.user.profile_image.url(:medium) %></B></td></tr>
  <tr>  <td align="center" colspan="3"><%= image_tag post.image.url(:thumb) %></td></tr>
  <tr style="background:gray">  <td align="left" colspan="3" style="font-size:20px"><B><%= post.content %></B><hr/></td></tr>
  <tr style="background:gray">  <td align="center" style="color:black"><B><%= link_to 'Show', post %></B></td>
        <td align="center" style="color:black"><B><%= link_to 'Edit', edit_post_path(post)%></B></td>
        <td align="center" style="color:black"><B><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></B></td></tr>
      <tr style="background:gray"><td colspan="3">&nbsp;&nbsp;</td></tr>
       </tbody>
</table>
<br>
    <% end %>
 <% else %>
  <p style="color:white"> User and him/her friends have no post....</p>
 <% end %> 
<br>


</center>
</div>
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE>
<html>
<head>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Poiret+One" %>
<%= stylesheet_link_tag "bootstrap/css/bootstrap.min" %>
	<style>   


  *{
  font-family: 'Poiret One';
}
body
{
  background-image: url('/assets/bg.jpg');
  color: #fff;
  
  background-size: cover;
}
     td{padding:6px;}

     
  .bg_color
  {
    height: 1000px;
    width: 100%;
    background-color: rgba(11,124,135,0.6) !important;
  }
  .links
  {
    color: #fff !important;
    font-size: 50px !important;
    font-weight: 100 !important;
    text-decoration: none !important;
    background: none;
  }
  .black_clr
  {
    color: #000;
  }
 input[type=submit]
  {
    background: none !important;
    border: 1px solid #fff !important;
    padding: 5px !important;
  }
a
{
    background: none !important;
    border: 1px solid #fff !important;
    padding: 7px !important;
    color: #fff !important;
    text-decoration: none !important;
    margin: 10px !important;
  }
 
  
</style>
</head>
<body>

<div class="bg_color">
<center>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      
    </div>
    <div class="col-md-6">
      <h1 style="font-size:60px;font-weight:100;margin-top:50px;">New POST</h1>
    </div>
  </div>
</div>
<%= render 'form' %></br>

<%= link_to 'Back', posts_path %>
</center>
</div>
</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<style>   
td{padding:6px;}
 .sbl
   {
    display:block;
    border:1px solid #999999;
    border-radius:5px;  
    min-width:auto; 
   }
  .links
  {
    color: black !important;
    font-size: 30px !important;
    font-weight: 100 !important;
    text-decoration: none !important;
    background: none;
  }
  a
{
    background: none !important;
    border: 1px solid blue !important;
    padding: 7px !important;
    color: blue !important;
    text-decoration: none !important;
  }
</style>
</head>
<body>

<center>
<fieldset class="sbl">
<p id="notice"><%= notice %></p>
<table border="0">
  <tr>
<p>
 <td> <strong>Attachment:</strong></td>
  <td><%= image_tag @post.image.url(:thumb) %>
</td>
</p>
</tr>
<tr>
<p>
  <td><strong>Content:</strong></td>
  <td><%= @post.content %></td>
</p>
</tr>
<tr>
<p>
 <td> <strong>User:</strong></td>
  <td><%= @post.user.email %></td>
</p><br>
</tr>
<tr><br>
	<td></td><br>
<td><%= link_to 'Edit', edit_post_path(@post), :class => 'links' %></td>
<td><%= link_to 'Feed', posts_path, :class => 'links' %></td>
</table>
</fieldset>
</center>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<!DOCTYPE>
<html>
<head>
<%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Poiret+One" %>
<%= stylesheet_link_tag "bootstrap/css/bootstrap.min" %>
 
<style>

*{
	font-family: 'Poiret One';
}
body
{
	background-image: url('/assets/bg.jpg');
	color: #fff;
	
	background-size: cover;
}
     td{padding:6px;}

     
	.bg_color
	{
		height: 1000px;
		width: 100%;
		background-color: rgba(11,124,135,0.6) !important;
	}
	.links
	{
		color: #fff !important;
		font-size: 50px !important;
		font-weight: 100 !important;
		text-decoration: none !important;
		background: none;
	}
</style>
</head>
<body>
<div class="bg_color">
<center>

<div class="container">
	<div class="row">
		<div class="col-md-10">
			
		</div>
		<div class="col-md-2">
			<h1 style="font-size:100px;font-weight:100;margin-top:50px;">FLISTER</h1>
		</div>
	</div>
</div>


<table border="0" style="margin-top:200px;">
<tr>
<% if user_signed_in? %>
 <h2 class="links"> Logged in as <strong><%= current_user.email %></strong>.</h2>
 <%= image_tag current_user.profile_image.url(:medium) %>
 <td><%= link_to 'Edit profile', edit_user_registration_path, :class => 'links' %></td><td class="links">|</td>
 <td><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'links'  %></td><td class="links">|</td>
 <td><%= link_to "Post", new_post_path, :class => 'links'  %></td><td class="links">|</td>
 <td><%= link_to "User", user_listing_path, :class => 'links'  %></td><td class="links">|</td>
 <td><%= link_to "Friend", friend_list_path, :class => 'links'  %></td><td class="links">|</td>
 <td><%= link_to 'Feed', posts_path, :class => 'links' %></td>
</tr>
<tr>
<% else %>
 <td> <%= link_to "Sign up", new_user_registration_path, :class => 'links'  %></td>
 <td class="links">|</td>
 <td> <%= link_to "Login", new_user_session_path, :class => 'links'  %>

 </td>

<% end %>

</tr>
</table>
</center>
</div>
</body>
</html>



app/views/welcome/user_listing.html.erb
<!DOCTYPE>
<html>
<head>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Poiret+One" %>
<%= stylesheet_link_tag "bootstrap/css/bootstrap.min" %>
<style>
    td{padding:6px;}
    th{padding:6px;}
 *{
  font-family: 'Poiret One';
}



     
  
  

</style>
</head>
<body>

<center>


<p id="notice"><B><%= notice %></B></p>

<h1><B>Listing User</B></h1>

<table border="0">
  <thead>
    <tr>
     
      <th align="center"><B>Email</B></th>
      <th align="center">Profile Image</th>
      <th align="center"><B>Action</B></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td align="center" style="font-size:20px;"><B><%= user.email %></B></td>
        <td><%= image_tag user.profile_image.url(:medium) %></th></td>
        <td align="center"><B><%= link_to "Add Friend", send_friend_request_path(:friend_id => user), :method => :post, :class => 'btn btn-primary' %></B>
		</td>
      </tr>
    <% end %>
    <td align="center">&nbsp;&nbsp;&nbsp;<B><%= link_to 'Back', root_path, :class => 'btn btn-primary' %></B></td>
  </tbody>
</table>

<br>

</center>

</body>
</html>